In [5]:
#Question 1
import numpy as np
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Question 2
matrix=np.arrange(9).reshape(3,3)
print(matrix)

In [7]:
#Question 3
identity_matrix=np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#Question 4
a4 = np.arange(27).reshape(3, 3, 3)
print(a4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [13]:
#Question 5
variable = np.random.randint(0, 100, (10, 10))
print(variable)
print(f'max value: {variable.max()}')
print(f'min value: {variable.min()}')


[[41 12  8 18 48  6 86 52 18 53]
 [69 59 78 35 47 57 78 92 28 49]
 [82 66 58 27 95 52 31 79 35 61]
 [24 40 25 20  7 56 34 36 67 96]
 [60 47 54 92 87 44 46 60 32 95]
 [73 76 84 27 43 58 11  4  6 65]
 [ 8 16 14 13 86 63 49 12 71 79]
 [ 1 98 16 10 46 66  4  0 30  8]
 [78 89 64 14 72 84  0  6 18 55]
 [23 49  5 90 24 77 14 92 29 57]]
max value: 98
min value: 0


In [ ]:
#Question 6
arr = np.random.randint(0, 10, 30)
print(arr.mean())

3.433333333333333


In [27]:
#Question 7
matrix = np.random.randint(0, 100, (5, 5))
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print( normalized_matrix)

[[0.02105263 0.77894737 0.90526316 0.48421053 0.51578947]
 [0.03157895 0.57894737 0.62105263 0.01052632 0.28421053]
 [0.8        0.95789474 0.4        0.66315789 0.03157895]
 [0.4        0.14736842 1.         0.         0.84210526]
 [0.01052632 0.91578947 0.11578947 0.6        0.63157895]]


In [28]:
#Question 8
i = np.random.randint(0, 10, (5, 3))
s = np.random.randint(0, 10, (3, 2))
print(i)
print(s)
print('Multiplied:')
print(i@s)

[[0 0 4]
 [9 0 5]
 [2 6 5]
 [3 1 5]
 [4 2 7]]
[[5 0]
 [1 3]
 [7 7]]
Multiplied:
[[28 28]
 [80 35]
 [51 53]
 [51 38]
 [71 55]]


In [29]:
#Question 9
m1 = np.random.randint(0, 10, (3, 3))
m2 = np.random.randint(0, 10, (3, 3))
print(m1)
print(m2)
print(np.dot(m1, m2))

[[4 8 1]
 [4 4 3]
 [3 4 1]]
[[4 4 8]
 [9 7 4]
 [2 6 4]]
[[90 78 68]
 [58 62 60]
 [50 46 44]]


In [30]:
#Question 10
tr = np.random.randint(0, 10, (4, 4))
print('Original:')
print(tr)
print('Transpose:')
print(tr.transpose())

Original:
[[2 7 0 7]
 [1 3 4 9]
 [4 9 8 8]
 [1 2 3 7]]
Transpose:
[[2 1 4 1]
 [7 3 9 2]
 [0 4 8 3]
 [7 9 8 7]]


In [31]:
#Question 11
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

det_A = np.linalg.det(A)

print(A)
print(det_A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [32]:
#Question 12
A = np.random.randint(1, 10, (3, 4))
B = np.random.randint(1, 10, (4, 3))
C = np.dot(A, B) 
print("Matrix A (3x4):\n", A)
print("Matrix B (4x3):\n", B)
print("Matrix Product C (3x3):\n", C)

Matrix A (3x4):
 [[7 1 1 4]
 [4 7 6 3]
 [1 8 6 6]]
Matrix B (4x3):
 [[7 5 3]
 [1 2 9]
 [6 7 8]
 [7 6 6]]
Matrix Product C (3x3):
 [[ 84  68  62]
 [ 92  94 141]
 [ 93  99 159]]


In [34]:
#Question 13
random_m=np.random.randint(0,10,(3,3))
random_v=np.random.randint(1, 10, (3, 1))
product=np.dot(random_m,random_v)
print(product)


[[38]
 [24]
 [27]]


In [35]:
#Question 14
A = np.array([[2, 3, 1], 
              [4, 5, 6], 
              [7, 8, 9]])
b = np.array([[1], 
              [2], 
              [3]])

x = np.linalg.solve(A, b)

print("Matrix A:\n", A)
print("Vector b:\n", b)
print("Solution x:\n", x)

Matrix A:
 [[2 3 1]
 [4 5 6]
 [7 8 9]]
Vector b:
 [[1]
 [2]
 [3]]
Solution x:
 [[-0.22222222]
 [ 0.44444444]
 [ 0.11111111]]


In [ ]:
#Question 15
A = np.random.randint(1, 10, (5, 5))
row_sums = np.sum(A, axis=1)
col_sums = np.sum(A, axis=0)

print("Matrix A (5x5):\n", A)
print("Row-wise sums:\n", row_sums)
print("Column-wise sums:\n", col_sums)